#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 140
# Replace DataTable plain-text empty state with EmptyState component

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task 140: DataTable EmptyState Enhancement"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend..."
cd frontend && npm run dev &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend"

# ============================================
# OPTIONAL: START BACKEND (if needed for full testing)
# ============================================

echo ""
echo -e "${YELLOW}Backend is not required for this UI-only task${NC}"
echo -e "${YELLOW}If you need full API integration, run separately:${NC}"
echo -e "${YELLOW}  cd backend && uvicorn app.main:app --reload --port 8000${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Task: Replace DataTable plain-text empty state"
echo "Files to modify:"
echo "  - frontend/src/components/ui/DataTable.tsx"
echo "  - frontend/src/pages/EquipmentPage.tsx (enhancement)"
echo "  - frontend/src/pages/MaterialsPage.tsx (optional cleanup)"
echo ""
echo "Next steps:"
echo "  1. Open DataTable.tsx and update props interface"
echo "  2. Replace plain-text empty render with EmptyState"
echo "  3. Test on all 5 DataTable pages"
echo ""
echo "Press Ctrl+C to stop all services"
wait
