#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Error Handling Infrastructure
# Spec: 025-no-error-handling-feedback-when-api-calls-fail

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Error Handling Infrastructure"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START BACKEND SERVICE
# ============================================

echo ""
echo "Starting Backend API..."
cd backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  Frontend:     http://localhost:3000"
echo ""
echo "Process IDs:"
echo "  Backend PID:  $BACKEND_PID"
echo "  Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "========================================"
echo "Ready for Error Handling Testing"
echo "========================================"
echo ""
echo "Test Scenarios:"
echo "  1. Navigate to http://localhost:3000/projects"
echo "  2. Try creating a project (should show success toast)"
echo "  3. Stop backend (kill $BACKEND_PID) and retry"
echo "  4. Verify error toast appears"
echo "  5. Set invalid token: localStorage.setItem('authToken', 'invalid')"
echo "  6. Make API call - should redirect to /login"
echo ""
