#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec: 001-3-6-seed-inspection-templates-from-excel-data

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START DATABASE
# ============================================

echo ""
echo "Starting PostgreSQL database..."
docker-compose up db -d
wait_for_service 5432 "PostgreSQL"

# ============================================
# START BACKEND
# ============================================

echo ""
echo "Starting Backend service..."
cd backend

# Install dependencies if needed
if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv venv
fi

source venv/bin/activate
pip install -q -r requirements.txt

# Run migrations
echo "Running database migrations..."
alembic upgrade head

# Start backend server in background
echo "Starting FastAPI server..."
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!

cd ..

wait_for_service 8000 "Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Database: postgresql://localhost:5432/builder_db"
echo "  Backend:  http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo ""
echo "Next Steps:"
echo "  1. Run seed script: cd backend && python -m app.db.seeds.inspection_templates"
echo "  2. View implementation plan: cat .auto-claude/specs/001-3-6-seed-inspection-templates-from-excel-data/implementation_plan.json"
echo ""
echo "To stop services:"
echo "  - Backend: kill $BACKEND_PID"
echo "  - Database: docker-compose down"
echo ""
