#!/bin/bash

# Auto-Build Environment Setup for Equipment Template API
# Generated by Planner Agent

set -e

echo "========================================"
echo "Equipment Template API - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# DATABASE CHECK
# ============================================

echo ""
echo "Checking database connection..."
cd backend
if ! python -c "from app.db.session import get_db; print('Database connection OK')" 2>/dev/null; then
    echo -e "${RED}Database connection failed. Make sure PostgreSQL is running.${NC}"
    echo "Run: docker-compose up -d db"
    exit 1
fi
echo -e "${GREEN}Database connected${NC}"

# ============================================
# APPLY MIGRATIONS
# ============================================

echo ""
echo "Checking database migrations..."
if ! alembic current 2>/dev/null; then
    echo -e "${YELLOW}No migrations applied yet${NC}"
fi

echo "To apply migrations, run:"
echo "  cd backend && alembic upgrade head"
echo ""

# ============================================
# START BACKEND
# ============================================

echo ""
echo "Starting FastAPI backend server..."
echo "Command: uvicorn app.main:app --reload --port 8000"
echo ""
echo -e "${YELLOW}Run this command in a separate terminal:${NC}"
echo "  cd backend && uvicorn app.main:app --reload --port 8000"
echo ""

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Development Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/api/v1/docs"
echo "  ReDoc:        http://localhost:8000/redoc"
echo ""
echo "Database:"
echo "  PostgreSQL:   localhost:5432"
echo ""
echo "Quick Start:"
echo "  1. Apply migrations: cd backend && alembic upgrade head"
echo "  2. Start backend:    cd backend && uvicorn app.main:app --reload --port 8000"
echo "  3. Open Swagger UI:  http://localhost:8000/api/v1/docs"
echo ""
echo "Testing:"
echo "  Unit tests:          cd backend && pytest tests/api/v1/test_equipment_templates.py -v"
echo "  Integration tests:   cd backend && pytest tests/integration/ -v"
echo "  All tests:           cd backend && pytest -v"
echo ""
