#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 044 - Mobile-First Responsive Design

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Mobile-First Responsive Design"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Frontend..."
cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
fi

# Start frontend dev server
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# OPTIONAL: Start Backend (if needed for testing)
# ============================================

# Uncomment below if backend is needed for responsive testing
# echo ""
# echo "Starting Backend..."
# cd ../backend
#
# if [ ! -d "venv" ]; then
#     echo -e "${YELLOW}Creating Python virtual environment...${NC}"
#     python -m venv venv
#     source venv/bin/activate
#     pip install -r requirements.txt
# else
#     source venv/bin/activate
# fi
#
# python -m uvicorn app.main:app --reload &
# BACKEND_PID=$!
#
# wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services Running:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Testing Responsive Design:"
echo "  1. Open Chrome DevTools (F12)"
echo "  2. Toggle device toolbar (Ctrl+Shift+M)"
echo "  3. Test viewports:"
echo "     - Mobile:  375x667 (iPhone SE)"
echo "     - Tablet:  768x1024 (iPad)"
echo "     - Desktop: 1280x720"
echo ""
echo "To stop services:"
echo "  Press Ctrl+C or run: kill $FRONTEND_PID"
echo ""
echo "========================================"

# Keep script running
wait
