#!/bin/bash

# Auto-Build Environment Setup
# Hebrew Translation Feature Implementation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Hebrew Translation Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START BACKEND SERVICE
# ============================================

echo ""
echo "Starting Backend (FastAPI)..."
cd ./backend

# Install dependencies if needed
if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv venv
fi

source venv/bin/activate

# Install/upgrade dependencies
pip install -q -r requirements.txt

# Run migrations
echo "Running database migrations..."
alembic upgrade head

# Start backend
echo "Backend starting on port 8000..."
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!

cd ..

# Wait for backend
wait_for_service 8000 "Backend API" || {
    kill $BACKEND_PID 2>/dev/null || true
    exit 1
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd ./frontend

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start frontend
echo "Frontend starting on port 3000..."
npm run dev &
FRONTEND_PID=$!

cd ..

# Wait for frontend
wait_for_service 3000 "Frontend Application" || {
    kill $FRONTEND_PID 2>/dev/null || true
    kill $BACKEND_PID 2>/dev/null || true
    exit 1
}

# ============================================
# CLEANUP FUNCTION
# ============================================

cleanup() {
    echo ""
    echo "Shutting down services..."
    kill $BACKEND_PID 2>/dev/null || true
    kill $FRONTEND_PID 2>/dev/null || true
    echo "Done."
}

trap cleanup EXIT INT TERM

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  Backend:  ${GREEN}http://localhost:8000${NC}"
echo -e "    API:    ${GREEN}http://localhost:8000/api/v1${NC}"
echo -e "    Docs:   ${GREEN}http://localhost:8000/api/v1/docs${NC}"
echo -e "  Frontend: ${GREEN}http://localhost:3000${NC}"
echo ""
echo "Database:"
echo "  PostgreSQL is running (from docker-compose if started separately)"
echo ""
echo "Next Steps:"
echo "  1. Open http://localhost:3000 in your browser"
echo "  2. Try switching between English and Hebrew (language selector in header)"
echo "  3. Verify RTL layout works correctly in Hebrew mode"
echo "  4. Test API endpoints with curl or Postman"
echo ""
echo "Example: Test login with Hebrew language"
echo "  curl -X POST http://localhost:8000/api/v1/auth/login \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -H 'Accept-Language: he' \\"
echo "    -d '{\"email\": \"test@example.com\", \"password\": \"wrong\"}'"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $BACKEND_PID $FRONTEND_PID 2>/dev/null || true
