#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Equipment Tracking Table Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Equipment Tracking Table Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK BACKEND (must already be running)
# ============================================

echo ""
echo "Checking for backend API..."
if ! nc -z localhost 8000 2>/dev/null; then
    echo -e "${YELLOW}WARNING: Backend API not detected on port 8000${NC}"
    echo "The equipment table requires the backend API to be running."
    echo "Please start the backend in a separate terminal:"
    echo "  cd backend && uvicorn app.main:app --reload"
    echo ""
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    echo -e "${GREEN}Backend API detected${NC}"
fi

# ============================================
# START FRONTEND
# ============================================

echo ""
echo "Starting frontend development server..."
cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi

# Start frontend dev server
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000 (external)"
echo "  API Docs: http://localhost:8000/docs"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Equipment Page:"
echo "  http://localhost:3000/projects/{projectId}/equipment"
echo ""
echo "Design Reference:"
echo "  ./design-assets/project/16-equipment-list.png"
echo ""
echo "Press Ctrl+C to stop the frontend server"
echo ""

# Wait for Ctrl+C
trap "echo 'Stopping services...'; kill $FRONTEND_PID 2>/dev/null; exit 0" INT
wait $FRONTEND_PID
