#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Offline Mode Interface
# Spec: 043-build-offline-mode-interface

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Offline Mode Interface Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd frontend
npm run dev:hmr &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Development Mode:"
echo "  - Hot Module Replacement enabled"
echo "  - TypeScript type checking active"
echo "  - React DevTools available"
echo ""
echo "Testing Offline Mode:"
echo "  1. Open http://localhost:3000 in Chrome/Edge"
echo "  2. Open DevTools (F12)"
echo "  3. Go to Network tab"
echo "  4. Toggle 'Offline' mode to test"
echo ""
echo "Press Ctrl+C to stop all services"
echo "========================================"

# Wait for Ctrl+C
wait $FRONTEND_PID
