#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Equipment Templates Migration

set -e

echo "========================================"
echo "Equipment Templates Migration Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting PostgreSQL database..."
docker-compose up -d db
wait_for_service 5432 "PostgreSQL"

echo ""
echo "Starting backend service..."
cd backend
uvicorn app.main:app --reload --port 8000 &
cd ..
wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Database: postgresql://localhost:5432"
echo "  Backend:  http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo ""
echo "Ready for migration:"
echo "  cd backend"
echo "  alembic revision --autogenerate -m \"add equipment templates\""
echo "  alembic upgrade head"
echo ""
