#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 028

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 028: Add Form Validation to Equipment Creation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Frontend (frontend-only task)..."
echo ""

# Frontend
cd frontend && npm run dev &
FRONTEND_PID=$!
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "To test:"
echo "  1. Navigate to http://localhost:3000"
echo "  2. Select a project"
echo "  3. Go to Equipment tab"
echo "  4. Click Add Equipment"
echo "  5. Test serial number validation"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for user interrupt
trap "echo 'Stopping services...'; kill $FRONTEND_PID 2>/dev/null; exit 0" INT TERM
wait
