#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 134

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Fix hardcoded en-US locale"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing frontend dependencies..."
cd frontend
if [ ! -d "node_modules" ]; then
    npm install
else
    echo "Dependencies already installed"
fi

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting frontend development server..."
npm run dev &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
echo "========================================"
echo "Ready to implement locale switching!"
echo "========================================"
