#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 048: Refactor Inspection History Timeline

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 048: Inspection History Timeline"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Backend Service..."
cd ./backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

echo ""
echo "Starting Frontend Service..."
cd ./frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services Running:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  Frontend:     http://localhost:3000"
echo ""
echo "Inspection Pages:"
echo "  http://localhost:3000/projects/[projectId]/inspections"
echo ""
echo "Design Reference:"
echo "  design-assets/inspection/25-history-timeline.png"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for Ctrl+C
trap "echo -e '${YELLOW}\nStopping services...${NC}'; kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; exit 0" SIGINT SIGTERM

wait
