#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 007-2-6

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Seed Checklist Templates from Excel Data"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting PostgreSQL database..."
docker-compose up db -d
wait_for_service 5432 "PostgreSQL"

echo ""
echo "Starting Backend service..."
cd backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..
wait_for_service 8000 "Backend"

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo ""
echo "Verifying openpyxl dependency..."
cd backend
if ! pip list | grep -q openpyxl; then
    echo -e "${YELLOW}openpyxl not installed. Installing dependencies...${NC}"
    pip install -r requirements.txt
else
    echo -e "${GREEN}openpyxl already installed${NC}"
fi
cd ..

# ============================================
# RUN DATABASE MIGRATIONS
# ============================================

echo ""
echo "Running database migrations..."
cd backend
alembic upgrade head
cd ..

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL: localhost:5432"
echo "  Backend API: http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo ""
echo "To run the seed script:"
echo "  cd backend && python -m app.db.seeds.checklist_templates"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo "  docker-compose down"
echo ""
