#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 029
# Task: Authentication Security Verification

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 029: Authentication Verification"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -n "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e " ${RED}FAILED${NC}"
            echo -e "${RED}$name failed to start after 30 seconds${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo -e " ${GREEN}OK${NC}"
}

# Check if required commands exist
command -v nc >/dev/null 2>&1 || { echo -e "${RED}Error: 'nc' command not found. Please install netcat.${NC}"; exit 1; }

# ============================================
# START BACKEND
# ============================================
echo ""
echo -e "${YELLOW}Starting Backend Service...${NC}"
cd /Users/galhadida/projects/builder_project/builder_program/backend

# Check if virtual environment exists
if [ ! -d ".venv" ]; then
    echo -e "${YELLOW}Backend virtual environment not found. Creating...${NC}"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
else
    source .venv/bin/activate
fi

# Start backend in background
nohup uvicorn app.main:app --reload --port 8000 > /tmp/backend-029.log 2>&1 &
BACKEND_PID=$!
echo "Backend PID: $BACKEND_PID"

# Wait for backend to be ready
wait_for_service 8000 "Backend API" || exit 1

# ============================================
# START FRONTEND
# ============================================
echo ""
echo -e "${YELLOW}Starting Frontend Service...${NC}"
cd /Users/galhadida/projects/builder_project/builder_program/frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Frontend dependencies not found. Installing...${NC}"
    npm install
fi

# Start frontend in background
nohup npm run dev > /tmp/frontend-029.log 2>&1 &
FRONTEND_PID=$!
echo "Frontend PID: $FRONTEND_PID"

# Wait for frontend to be ready
wait_for_service 3000 "Frontend Dev Server" || exit 1

# ============================================
# SUMMARY
# ============================================
echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services Running:"
echo "  Backend API:    http://localhost:8000"
echo "  API Docs:       http://localhost:8000/docs"
echo "  Frontend:       http://localhost:3000"
echo ""
echo "Process IDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "Logs:"
echo "  Backend:  tail -f /tmp/backend-029.log"
echo "  Frontend: tail -f /tmp/frontend-029.log"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo -e "${YELLOW}Ready for authentication verification testing!${NC}"
echo "Open http://localhost:3000/login to begin manual testing."
echo ""
