#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Create Alembic Migration for Checklist Templates

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting PostgreSQL database..."
docker-compose up -d db
wait_for_service 5432 "PostgreSQL"

echo ""
echo "PostgreSQL is ready. You can now run Alembic migrations:"
echo ""
echo -e "${GREEN}cd backend${NC}"
echo -e "${GREEN}alembic upgrade head${NC}"
echo ""

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL: localhost:5432 (database: builder_db)"
echo ""
echo "To run the migration:"
echo "  1. cd backend"
echo "  2. alembic upgrade head"
echo ""
echo "To verify tables created:"
echo "  docker exec -it builder_db psql -U postgres -d builder_db -c \"\\dt checklist*\""
echo ""
echo "To verify indexes:"
echo "  docker exec -it builder_db psql -U postgres -d builder_db -c \"\\di checklist*\""
echo ""
