#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 113 - Add Hebrew Language Support

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Add Hebrew Language Support"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Change to project root
cd "$(dirname "$0")/../../.."

# Frontend
echo ""
echo "Starting Frontend (React + Vite)..."
cd frontend
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "To test RTL support:"
echo "  1. Open http://localhost:3000 in browser"
echo "  2. Click the language icon in the header"
echo "  3. Select Hebrew (עברית)"
echo "  4. Verify layout flips to RTL"
echo ""
echo "Process IDs:"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
