#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for RFI System Integration Tests

set -e

echo "========================================"
echo "RFI Integration Tests - Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# BACKEND TEST ENVIRONMENT
# ============================================

echo ""
echo -e "${YELLOW}Setting up backend test environment...${NC}"
cd backend

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    python3 -m venv venv
fi

# Activate virtual environment
echo -e "${YELLOW}Activating virtual environment...${NC}"
source venv/bin/activate

# Install/update dependencies
echo -e "${YELLOW}Installing test dependencies...${NC}"
pip install -q -r requirements.txt
pip install -q -r requirements-test.txt 2>/dev/null || true

# Verify pytest is available
if ! command -v pytest &> /dev/null; then
    echo -e "${RED}pytest not found, installing...${NC}"
    pip install pytest pytest-asyncio pytest-cov pytest-mock
fi

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo -e "${YELLOW}Verifying test environment...${NC}"

# Check Python version
PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
echo -e "Python version: ${GREEN}${PYTHON_VERSION}${NC}"

# Check pytest
PYTEST_VERSION=$(pytest --version 2>&1 | head -n1)
echo -e "Pytest: ${GREEN}${PYTEST_VERSION}${NC}"

# Check key packages
echo ""
echo -e "${YELLOW}Checking RFI system dependencies...${NC}"
python -c "import fastapi; print('✓ FastAPI installed')" 2>/dev/null || echo -e "${RED}✗ FastAPI missing${NC}"
python -c "import sqlalchemy; print('✓ SQLAlchemy installed')" 2>/dev/null || echo -e "${RED}✗ SQLAlchemy missing${NC}"
python -c "import pytest_asyncio; print('✓ pytest-asyncio installed')" 2>/dev/null || echo -e "${RED}✗ pytest-asyncio missing${NC}"
python -c "import httpx; print('✓ httpx installed')" 2>/dev/null || echo -e "${RED}✗ httpx missing${NC}"

# Check if Google packages are installed (might be missing initially)
echo ""
echo -e "${YELLOW}Checking Google API packages (might be missing)...${NC}"
python -c "import googleapiclient; print('✓ google-api-python-client installed')" 2>/dev/null || echo -e "${YELLOW}⚠ google-api-python-client not installed (will be added)${NC}"
python -c "import google.auth; print('✓ google-auth installed')" 2>/dev/null || echo -e "${YELLOW}⚠ google-auth not installed (will be added)${NC}"
python -c "import google.cloud.pubsub; print('✓ google-cloud-pubsub installed')" 2>/dev/null || echo -e "${YELLOW}⚠ google-cloud-pubsub not installed (will be added)${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Test Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Review implementation_plan.json for subtasks"
echo "  2. Add missing dependencies to requirements.txt"
echo "  3. Create test fixtures in tests/conftest.py"
echo "  4. Write integration tests in tests/integration/test_rfi_system.py"
echo ""
echo "Run Tests:"
echo "  pytest backend/tests/integration/test_rfi_system.py -v"
echo ""
echo "Check Coverage:"
echo "  pytest backend/tests/integration/test_rfi_system.py --cov=app/services/rfi_service --cov=app/api/v1/rfis --cov-report=html"
echo ""
