#!/bin/bash

# Auto-Build Environment Setup
# Fix non-functional DataTable column sorting
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "DataTable Sorting Fix"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd ./frontend

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start frontend
echo "Frontend starting on port 3000..."
npm run dev &
FRONTEND_PID=$!

cd ..

# Wait for frontend
wait_for_service 3000 "Frontend Application" || {
    kill $FRONTEND_PID 2>/dev/null || true
    exit 1
}

# ============================================
# CLEANUP FUNCTION
# ============================================

cleanup() {
    echo ""
    echo "Shutting down services..."
    kill $FRONTEND_PID 2>/dev/null || true
    echo "Done."
}

trap cleanup EXIT INT TERM

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  Frontend: ${GREEN}http://localhost:3000${NC}"
echo ""
echo "Testing Instructions:"
echo "  1. Navigate to Inspections page: http://localhost:3000/inspections"
echo "  2. Click on the 'Scheduled Date' column header"
echo "  3. Verify that rows reorder based on date (ascending)"
echo "  4. Click again to reverse sort (descending)"
echo "  5. Check that the arrow indicator matches the sort order"
echo "  6. Test pagination - ensure sorted order is preserved across pages"
echo ""
echo "Note: This is a frontend-only fix. Backend is not required for testing."
echo ""
echo "Press Ctrl+C to stop the frontend service"
echo ""

# Keep script running
wait $FRONTEND_PID 2>/dev/null || true
