#!/bin/bash

# Auto-Build Environment Setup for Gantt Timeline Chart
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + TypeScript + Vite)..."
cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
fi

# Start development server in background
npm run dev > ../frontend-dev.log 2>&1 &
FRONTEND_PID=$!

cd ..

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}Services:${NC}"
echo "  Frontend:  http://localhost:3000"
echo ""
echo -e "${YELLOW}Logs:${NC}"
echo "  Frontend:  tail -f frontend-dev.log"
echo ""
echo -e "${YELLOW}Process IDs:${NC}"
echo "  Frontend:  $FRONTEND_PID"
echo ""
echo -e "${YELLOW}To stop services:${NC}"
echo "  kill $FRONTEND_PID"
echo ""
echo "========================================"
echo "Ready to implement Gantt Timeline Chart!"
echo "========================================"
