from fastapi import APIRouter
from app.api.v1 import projects, equipment, equipment_templates, material_templates, materials, meetings, approvals, areas, contacts, files, audit, auth, checklist_templates, analytics, rfis, webhooks, notifications, workload, consultant_types, document_reviews, document_analysis

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(projects.router, prefix="/projects", tags=["projects"])
api_router.include_router(equipment.router, tags=["equipment"])
api_router.include_router(equipment_templates.router, tags=["equipment_templates"])
api_router.include_router(material_templates.router, tags=["material_templates"])
api_router.include_router(materials.router, tags=["materials"])
api_router.include_router(meetings.router, tags=["meetings"])
api_router.include_router(approvals.router, tags=["approvals"])
api_router.include_router(areas.router, tags=["areas"])
api_router.include_router(contacts.router, tags=["contacts"])
api_router.include_router(files.router, tags=["files"])
api_router.include_router(audit.router, tags=["audit"])
api_router.include_router(checklist_templates.router, tags=["checklist_templates"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(rfis.router, tags=["rfis"])
api_router.include_router(webhooks.router, prefix="/webhooks", tags=["webhooks"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(workload.router, tags=["workload"])
api_router.include_router(consultant_types.router, tags=["consultant_types"])
api_router.include_router(document_reviews.router, tags=["document_reviews"])
api_router.include_router(document_analysis.router, tags=["document_analysis"])
