#!/bin/bash

# Auto-Build Environment Setup - Document Review Interface
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Document Review Interface - Spec 060"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check PostgreSQL
if ! command -v psql &> /dev/null; then
    echo -e "${YELLOW}Warning: psql not found. Ensure PostgreSQL is installed.${NC}"
fi

# Check Python
if ! command -v python &> /dev/null; then
    echo -e "${RED}Error: Python not found. Please install Python 3.10+${NC}"
    exit 1
fi

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js not found. Please install Node.js 18+${NC}"
    exit 1
fi

echo -e "${GREEN}Prerequisites check passed${NC}"

# ============================================
# START BACKEND
# ============================================

echo ""
echo "Starting Backend (FastAPI)..."

cd backend

# Activate virtual environment
if [ -d "venv" ]; then
    source venv/bin/activate
elif [ -d "test_env" ]; then
    source test_env/bin/activate
else
    echo -e "${YELLOW}Warning: No virtual environment found${NC}"
fi

# Run database migrations
echo "Running database migrations..."
alembic upgrade head

# Start backend server
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!

cd ..

wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND
# ============================================

echo ""
echo "Starting Frontend (Next.js)..."

cd frontend

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi

# Start frontend dev server
npm run dev &
FRONTEND_PID=$!

cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Document Review Interface:"
echo "  Route: /projects/{id}/documents/{documentId}/review"
echo ""
echo "Process IDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop all services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "========================================"
