#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Material Inventory Grid Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Material Inventory Grid Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START BACKEND SERVICE
# ============================================

echo ""
echo "Starting Backend (FastAPI)..."
cd backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo "  Frontend: http://localhost:3000"
echo ""
echo "To view materials:"
echo "  http://localhost:3000/projects/<PROJECT_ID>/materials"
echo ""
echo "Design Reference:"
echo "  ./design-assets/project/17-material-inventory.png"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop all services${NC}"
echo ""

# Wait for interrupt
wait
