#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 122: Gantt Timeline Chart

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 122 - Gantt Timeline Chart"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Frontend service..."
cd /Users/galhadida/projects/builder_project/builder_program/frontend
npm run dev:hmr &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Gantt Timeline Development:"
echo "  - Navigate to: http://localhost:3000/projects/1/timeline"
echo "  - Design Reference: ./design-assets/project/18-gantt-timeline.png"
echo ""
echo "Process IDs:"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop all services:"
echo "  kill $FRONTEND_PID"
echo ""
