#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 026: Add Form Validation to Areas Creation

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Add Form Validation to Areas Creation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${YELLOW}Starting Backend API...${NC}"
cd backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..
wait_for_service 8000 "Backend API"

echo ""
echo -e "${YELLOW}Starting Frontend Dev Server...${NC}"
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  Frontend:     http://localhost:3000"
echo ""
echo "Test the Areas form at:"
echo "  http://localhost:3000/projects/{project-id}/areas"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "Press Ctrl+C to stop all services"
echo "========================================"

# Keep script running
wait
