#!/bin/bash

# Auto-Build Environment Setup - RTL and Internationalization
# Generated by Planner Agent

set -e

echo "========================================"
echo "RTL and i18n Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Pre-flight checks..."

# Check Node.js installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js not found. Please install Node.js 18+${NC}"
    exit 1
fi

# Check npm installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm not found. Please install npm${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Node.js $(node --version)${NC}"
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check if frontend directory exists
if [ ! -d "frontend" ]; then
    echo -e "${RED}Error: frontend directory not found${NC}"
    exit 1
fi

# Check if node_modules exists
if [ ! -d "frontend/node_modules" ]; then
    echo -e "${YELLOW}node_modules not found. Running npm install...${NC}"
    cd frontend && npm install && cd ..
fi

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting frontend service..."
cd frontend && npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Development Notes:"
echo "  - i18n infrastructure already configured"
echo "  - Translation files: frontend/src/i18n/locales/{en,he}.json"
echo "  - Language switcher in Header (globe icon)"
echo "  - Test RTL: Click language toggle → Select עברית"
echo ""
echo "To stop services: Ctrl+C"
echo ""
echo "Process IDs:"
echo "  Frontend: $FRONTEND_PID"
echo ""
