#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Create ProjectInspection and InspectionFinding Models

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Start PostgreSQL and Redis via Docker Compose
echo ""
echo "Starting PostgreSQL and Redis..."
docker-compose up -d db redis

# Wait for database
wait_for_service 5432 "PostgreSQL"
wait_for_service 6379 "Redis"

# Start Backend (runs migrations automatically via docker-compose)
echo ""
echo "Starting Backend API..."
docker-compose up -d backend

# Wait for backend
wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL: localhost:5432"
echo "  Redis:      localhost:6379"
echo "  Backend:    http://localhost:8000"
echo "  API Docs:   http://localhost:8000/docs"
echo ""
echo "Database credentials:"
echo "  User:     postgres"
echo "  Password: postgres"
echo "  Database: builder_db"
echo ""
echo "To check logs:"
echo "  docker-compose logs -f backend"
echo ""
echo "To connect to database:"
echo "  docker exec -it builder_db psql -U postgres -d builder_db"
echo ""
