#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 061: Approval Workflow Stepper

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 061: Approval Workflow Stepper"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Frontend (primary service for this task)
echo ""
echo "Starting Frontend service..."
cd frontend
npm run dev &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend"

# Backend (optional - for API testing only)
echo ""
echo "Backend API (optional for testing):"
echo "  To start: cd backend && source venv/bin/activate && uvicorn app.main:app --reload"
echo "  Not starting automatically for this frontend-only task"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:8000 (manual start if needed)"
echo "  API Docs:  http://localhost:8000/docs"
echo ""
echo "This task modifies:"
echo "  - frontend/src/components/ui/Stepper.tsx (add ApprovalWorkflowStepper)"
echo ""
echo "Design reference:"
echo "  - design-assets/approval/26-approval-stepper.png"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
