#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 138: Translate Sidebar i18n

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Translate Sidebar navigation labels"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL FRONTEND DEPENDENCIES
# ============================================

echo ""
echo "Installing frontend dependencies..."
cd frontend
npm install

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting frontend development server..."
npm run dev &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop:"
echo "  kill $FRONTEND_PID"
echo ""
echo "Next steps:"
echo "  1. Install i18n packages (npm install react-i18next i18next)"
echo "  2. Create i18n config and translation files"
echo "  3. Update Sidebar component to use translations"
echo "  4. Test language switching in browser"
echo ""
