#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 031 - Add Date Validation to Create Project Dialog

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Add Date Validation to Create Project Dialog"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${YELLOW}Starting Frontend...${NC}"
cd frontend && npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "To test the feature:"
echo "  1. Navigate to http://localhost:3000/projects"
echo "  2. Click 'New Project' button"
echo "  3. Fill in required fields (name, code)"
echo "  4. Set Start Date to a future date"
echo "  5. Set End Date to a date BEFORE the start date"
echo "  6. Observe error message and disabled submit button"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $FRONTEND_PID
