#!/bin/bash

# Auto-Build Environment Setup - Finding Documentation Card
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 118 - Finding Documentation Card"
echo "========================================"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo "$name failed to start"
            return 1
        fi
        sleep 1
    done
    echo "$name ready"
}

# ============================================
# START SERVICES
# ============================================

# Frontend (React + Vite)
echo "Starting Frontend..."
cd ./frontend && npm run dev &
wait_for_service 3000 "Frontend"

# Note: Backend not started - this spec is frontend-only
echo "Backend not started (not needed for this spec)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Next Steps:"
echo "  1. Navigate to InspectionsPage to test component"
echo "  2. View design reference: design-assets/inspection/22-finding-card.png"
echo ""
