#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Team Workload View Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START BACKEND SERVICE
# ============================================

echo ""
echo -e "${YELLOW}Starting Backend Service...${NC}"
cd backend
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
cd ..
wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo -e "${YELLOW}Starting Frontend Service...${NC}"
cd frontend
npm run dev &
cd ..
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  Frontend:     http://localhost:3000"
echo ""
echo "Team Workload View will be accessible at:"
echo "  http://localhost:3000/team-workload"
echo ""
echo -e "${YELLOW}Note: Frontend may take a few moments to compile${NC}"
echo ""
