#!/bin/bash

# Auto-Build Environment Setup
# Task: 053-create-document-library
# Generated by Planner Agent

set -e

echo "========================================"
echo "Document Library - Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd frontend
npm run dev &
FRONTEND_PID=$!

wait_for_service 3000 "Frontend"

# ============================================
# OPTIONAL: START BACKEND (if needed for testing)
# ============================================

echo ""
echo -e "${YELLOW}Note: Backend API is not required for component development${NC}"
echo -e "${YELLOW}If you need to test file uploads, start backend separately:${NC}"
echo -e "${YELLOW}  cd backend && uvicorn app.main:app --reload --port 8000${NC}"
echo ""

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:8000 (start manually if needed)"
echo ""
echo "To stop services:"
echo "  Press Ctrl+C"
echo ""
echo "Next Steps:"
echo "  1. Start implementing subtasks from implementation_plan.json"
echo "  2. Begin with phase-1-components (Core Components)"
echo "  3. Verify each subtask with: cd frontend && npm run build"
echo ""
