#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Equipment Approval Template System (Schemas Only)

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Equipment Approval Template System - Schemas Only"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo "Starting Backend (FastAPI)..."
cd backend && uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
wait_for_service 8000 "Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo ""
echo "Note: This task only creates Pydantic schemas."
echo "No database or API endpoints are modified."
echo ""
echo "To verify schemas:"
echo "  cd backend"
echo "  python -c 'from app.schemas.inspection_template import EquipmentTemplateCreate; print(\"OK\")'"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo ""
