#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for BUI-75: Create Finding Documentation Card

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: Finding Documentation Card"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd frontend
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Development Notes:"
echo "  - Finding type already exists in types/index.ts"
echo "  - SeverityBadge component already exists in ui/StatusBadge.tsx"
echo "  - Use StyledCard pattern from ui/Card.tsx"
echo "  - Photos are string[] URLs (not Photo objects)"
echo ""
echo "Reference Design:"
echo "  - See: 22-finding-card.png"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
