#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Analytics Dashboard Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Analytics Dashboard Feature (BUI-61)"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL FRONTEND DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Installing frontend dependencies...${NC}"
cd frontend
npm install @mui/x-charts jspdf html2canvas
cd ..

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${YELLOW}Starting backend service...${NC}"
cd backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..
wait_for_service 8000 "Backend API"

echo ""
echo -e "${YELLOW}Starting frontend service...${NC}"
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API: http://localhost:8000"
echo "  API Docs:    http://localhost:8000/docs"
echo "  Frontend:    http://localhost:3000"
echo "  Analytics:   http://localhost:3000/analytics"
echo ""
echo "Process IDs:"
echo "  Backend PID:  $BACKEND_PID"
echo "  Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "Next steps:"
echo "  1. Verify services are running at URLs above"
echo "  2. Check backend API docs at http://localhost:8000/docs"
echo "  3. Navigate to analytics dashboard at http://localhost:3000/analytics"
echo ""
