#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for RTL Layout Support

set -e

echo "========================================"
echo "Starting Development Environment"
echo "RTL Layout Support Implementation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing RTL dependencies..."
cd frontend
npm install @mui/stylis-plugin-rtl @emotion/cache stylis
echo -e "${GREEN}Dependencies installed${NC}"

# ============================================
# START SERVICES
# ============================================

# Frontend
echo ""
echo "Starting frontend development server..."
npm run dev &
FRONTEND_PID=$!
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "RTL Implementation:"
echo "  - Install RTL dependencies ✓"
echo "  - Configure Emotion cache in ThemeContext"
echo "  - Migrate rtl.css to logical properties"
echo "  - Update component sx props to logical properties"
echo "  - Test RTL layout with Hebrew language"
echo ""
echo "Reference Design: design-assets/29-hebrew-rtl.png"
echo ""
echo "To test RTL:"
echo "  1. Open http://localhost:3000"
echo "  2. Click LanguageToggle (globe icon)"
echo "  3. Select Hebrew (עברית)"
echo "  4. Verify layout matches reference design"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $FRONTEND_PID
