#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 133: Field Inspector Mobile Dashboard

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Field Inspector Mobile Dashboard"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START BACKEND (needed for API)
# ============================================

echo ""
echo "Starting Backend API..."
cd backend
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000 (API)"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Inspector Dashboard:"
echo "  URL: http://localhost:3000/inspector-dashboard"
echo ""
echo "Design Reference:"
echo "  File: design-assets/dashboard/10-inspector-mobile.png"
echo ""
echo "Process IDs:"
echo "  Backend PID:  $BACKEND_PID"
echo "  Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
