#!/bin/bash

# Auto-Build Environment Setup - Team Members Directory
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Backend
echo -e "${YELLOW}Starting Backend (FastAPI)...${NC}"
cd backend && uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

# Wait for backend to be ready
wait_for_service 8000 "Backend"

# Frontend
echo -e "${YELLOW}Starting Frontend (Vite)...${NC}"
cd frontend && npm run dev &
FRONTEND_PID=$!
cd ..

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Team Members API:"
echo "  GET http://localhost:8000/api/v1/team-members"
echo ""
echo "Frontend Routes:"
echo "  Dashboard:    http://localhost:3000/dashboard"
echo "  Team Members: http://localhost:3000/team-members (new)"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Trap SIGINT to kill both services
trap "echo 'Stopping services...'; kill $BACKEND_PID $FRONTEND_PID; exit" SIGINT

# Wait for both processes
wait
