#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Project Overview Page Feature
# Spec: 058-create-project-overview-page

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Project Overview Page Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check if PostgreSQL is running
if ! pg_isready -h localhost -p 5432 >/dev/null 2>&1; then
    echo -e "${YELLOW}Warning: PostgreSQL doesn't appear to be running${NC}"
    echo "Please start PostgreSQL before continuing"
fi

# Check Python virtual environment for backend
if [ ! -d "./backend/venv" ]; then
    echo -e "${YELLOW}Backend virtual environment not found${NC}"
    echo "Creating virtual environment..."
    cd backend
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    cd ..
fi

# Check frontend node_modules
if [ ! -d "./frontend/node_modules" ]; then
    echo -e "${YELLOW}Frontend node_modules not found${NC}"
    echo "Installing frontend dependencies..."
    cd frontend
    npm install
    cd ..
fi

# ============================================
# START BACKEND SERVICE
# ============================================

echo ""
echo "Starting Backend API (FastAPI)..."
cd backend
source venv/bin/activate
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (Next.js)..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  Frontend:     http://localhost:3000"
echo ""
echo "Project Overview Page will be available at:"
echo "  http://localhost:3000/projects/[id]/overview"
echo ""
echo "Process IDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "========================================"
echo "Ready for implementation!"
echo "========================================"
