#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 011-2-2

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: ChecklistInstance Models"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Start PostgreSQL via Docker
echo "Starting PostgreSQL database..."
docker-compose up -d db
sleep 3

# Backend
echo "Starting Backend API..."
cd backend && uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  PostgreSQL:   localhost:5432"
echo ""
echo "Process IDs:"
echo "  Backend: $BACKEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo "  docker-compose down"
echo ""
