"""Add inspection system tables

Revision ID: b348f02ac109
Revises: 003
Create Date: 2026-01-30 12:19:41.373028

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b348f02ac109'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultant_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_he', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultant_types_category'), 'consultant_types', ['category'], unique=False)
    op.create_table('equipment_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_he', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submission_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_templates_category'), 'equipment_templates', ['category'], unique=False)
    op.create_table('inspection_consultant_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_he', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_template_consultants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('consultant_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_type_id'], ['consultant_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['equipment_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_stage_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultant_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_he', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_type_id'], ['inspection_consultant_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultant_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('required_documentation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_type_id'], ['inspection_consultant_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_approval_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checklist_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['equipment_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['equipment_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('consultant_type_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('current_stage', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['consultant_type_id'], ['inspection_consultant_types.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['equipment_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_approval_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('consultant_type_id', sa.UUID(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['consultant_type_id'], ['consultant_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['equipment_approval_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('approval_requests', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('approval_requests', 'current_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('approval_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_steps', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('area_progress', 'progress_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('area_progress', 'reported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_constraint(op.f('audit_logs_project_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'projects', ['project_id'], ['id'])
    op.add_column('checklist_instances', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('checklist_instances', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('checklist_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_checklist_instances_area_id'), 'checklist_instances', ['area_id'], unique=False)
    op.create_index(op.f('ix_checklist_instances_project_id'), 'checklist_instances', ['project_id'], unique=False)
    op.create_index(op.f('ix_checklist_instances_status'), 'checklist_instances', ['status'], unique=False)
    op.create_index(op.f('ix_checklist_instances_template_id'), 'checklist_instances', ['template_id'], unique=False)
    op.drop_constraint(op.f('checklist_instances_completed_by_fkey'), 'checklist_instances', type_='foreignkey')
    op.drop_constraint(op.f('checklist_instances_template_id_fkey'), 'checklist_instances', type_='foreignkey')
    op.create_foreign_key(None, 'checklist_instances', 'checklist_templates', ['template_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'checklist_instances', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('checklist_instances', 'additional_data')
    op.drop_column('checklist_instances', 'completed_by')
    op.drop_column('checklist_instances', 'unit_identifier')
    op.drop_column('checklist_instances', 'started_at')
    op.add_column('checklist_item_responses', sa.Column('response_value', sa.Text(), nullable=True))
    op.add_column('checklist_item_responses', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('checklist_item_responses', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('checklist_item_responses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('checklist_item_responses', 'responded_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_checklist_item_responses_instance_id'), 'checklist_item_responses', ['instance_id'], unique=False)
    op.create_index(op.f('ix_checklist_item_responses_item_template_id'), 'checklist_item_responses', ['item_template_id'], unique=False)
    op.create_unique_constraint('unique_instance_item', 'checklist_item_responses', ['instance_id', 'item_template_id'])
    op.drop_constraint(op.f('checklist_item_responses_responded_by_fkey'), 'checklist_item_responses', type_='foreignkey')
    op.drop_constraint(op.f('checklist_item_responses_item_template_id_fkey'), 'checklist_item_responses', type_='foreignkey')
    op.create_foreign_key(None, 'checklist_item_responses', 'checklist_item_templates', ['item_template_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'checklist_item_responses', 'users', ['responded_by'], ['id'], ondelete='SET NULL')
    op.drop_column('checklist_item_responses', 'status')
    op.drop_column('checklist_item_responses', 'additional_data')
    op.drop_column('checklist_item_responses', 'note')
    op.drop_column('checklist_item_responses', 'image_file_ids')
    op.drop_column('checklist_item_responses', 'signature_file_id')
    op.add_column('checklist_item_templates', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('checklist_item_templates', sa.Column('item_type', sa.String(), nullable=False))
    op.add_column('checklist_item_templates', sa.Column('required', sa.Boolean(), nullable=False))
    op.add_column('checklist_item_templates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('checklist_item_templates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_checklist_item_templates_order'), 'checklist_item_templates', ['order'], unique=False)
    op.create_index(op.f('ix_checklist_item_templates_sub_section_id'), 'checklist_item_templates', ['sub_section_id'], unique=False)
    op.drop_column('checklist_item_templates', 'file_names')
    op.drop_column('checklist_item_templates', 'category')
    op.drop_column('checklist_item_templates', 'must_note')
    op.drop_column('checklist_item_templates', 'name')
    op.drop_column('checklist_item_templates', 'must_signature')
    op.drop_column('checklist_item_templates', 'name_he')
    op.drop_column('checklist_item_templates', 'additional_config')
    op.drop_column('checklist_item_templates', 'description')
    op.drop_column('checklist_item_templates', 'must_image')
    op.add_column('checklist_sub_sections', sa.Column('title', sa.String(), nullable=False))
    op.add_column('checklist_sub_sections', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('checklist_sub_sections', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('checklist_sub_sections', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_checklist_sub_sections_order'), 'checklist_sub_sections', ['order'], unique=False)
    op.create_index(op.f('ix_checklist_sub_sections_template_id'), 'checklist_sub_sections', ['template_id'], unique=False)
    op.drop_column('checklist_sub_sections', 'name')
    op.drop_column('checklist_sub_sections', 'name_he')
    op.add_column('checklist_templates', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('checklist_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_checklist_templates_group_name'), 'checklist_templates', ['group_name'], unique=False)
    op.create_index(op.f('ix_checklist_templates_level'), 'checklist_templates', ['level'], unique=False)
    op.drop_column('checklist_templates', 'description_file')
    op.drop_column('checklist_templates', 'logo_name')
    op.drop_column('checklist_templates', 'is_active')
    op.drop_column('checklist_templates', 'category')
    op.drop_column('checklist_templates', 'name_he')
    op.alter_column('construction_areas', 'total_units',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('construction_areas', 'current_progress',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('construction_areas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('contacts', sa.Column('contact_type', sa.String(length=50), nullable=False))
    op.add_column('contacts', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('contact_name', sa.String(length=255), nullable=False))
    op.add_column('contacts', sa.Column('role_description', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('is_primary', sa.Boolean(), nullable=False))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('contacts', 'name')
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'role')
    op.drop_column('contacts', 'company')
    op.alter_column('equipment', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('equipment', 'installation_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('equipment', 'warranty_expiry',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_checklists', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('equipment_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_attendees', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('unique_project_member'), 'project_members', type_='unique')
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(op.f('unique_project_member'), 'project_members', ['project_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('project_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meetings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('meeting_attendees', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_checklists', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('equipment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment', 'warranty_expiry',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('equipment', 'installation_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('equipment', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('contacts', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'is_primary')
    op.drop_column('contacts', 'role_description')
    op.drop_column('contacts', 'contact_name')
    op.drop_column('contacts', 'company_name')
    op.drop_column('contacts', 'contact_type')
    op.alter_column('construction_areas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('construction_areas', 'current_progress',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('construction_areas', 'total_units',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('checklist_templates', sa.Column('name_he', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('checklist_templates', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('checklist_templates', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('checklist_templates', sa.Column('logo_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('checklist_templates', sa.Column('description_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_checklist_templates_level'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_group_name'), table_name='checklist_templates')
    op.alter_column('checklist_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('checklist_templates', 'description')
    op.add_column('checklist_sub_sections', sa.Column('name_he', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('checklist_sub_sections', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_checklist_sub_sections_template_id'), table_name='checklist_sub_sections')
    op.drop_index(op.f('ix_checklist_sub_sections_order'), table_name='checklist_sub_sections')
    op.drop_column('checklist_sub_sections', 'updated_at')
    op.drop_column('checklist_sub_sections', 'created_at')
    op.drop_column('checklist_sub_sections', 'description')
    op.drop_column('checklist_sub_sections', 'title')
    op.add_column('checklist_item_templates', sa.Column('must_image', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('checklist_item_templates', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('checklist_item_templates', sa.Column('additional_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('checklist_item_templates', sa.Column('name_he', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('checklist_item_templates', sa.Column('must_signature', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('checklist_item_templates', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('checklist_item_templates', sa.Column('must_note', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('checklist_item_templates', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('checklist_item_templates', sa.Column('file_names', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_checklist_item_templates_sub_section_id'), table_name='checklist_item_templates')
    op.drop_index(op.f('ix_checklist_item_templates_order'), table_name='checklist_item_templates')
    op.drop_column('checklist_item_templates', 'updated_at')
    op.drop_column('checklist_item_templates', 'created_at')
    op.drop_column('checklist_item_templates', 'required')
    op.drop_column('checklist_item_templates', 'item_type')
    op.drop_column('checklist_item_templates', 'text')
    op.add_column('checklist_item_responses', sa.Column('signature_file_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('checklist_item_responses', sa.Column('image_file_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('checklist_item_responses', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('checklist_item_responses', sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('checklist_item_responses', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checklist_item_responses', type_='foreignkey')
    op.drop_constraint(None, 'checklist_item_responses', type_='foreignkey')
    op.create_foreign_key(op.f('checklist_item_responses_item_template_id_fkey'), 'checklist_item_responses', 'checklist_item_templates', ['item_template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('checklist_item_responses_responded_by_fkey'), 'checklist_item_responses', 'users', ['responded_by'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('unique_instance_item', 'checklist_item_responses', type_='unique')
    op.drop_index(op.f('ix_checklist_item_responses_item_template_id'), table_name='checklist_item_responses')
    op.drop_index(op.f('ix_checklist_item_responses_instance_id'), table_name='checklist_item_responses')
    op.alter_column('checklist_item_responses', 'responded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('checklist_item_responses', 'updated_at')
    op.drop_column('checklist_item_responses', 'created_at')
    op.drop_column('checklist_item_responses', 'completed')
    op.drop_column('checklist_item_responses', 'response_value')
    op.add_column('checklist_instances', sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('checklist_instances', sa.Column('unit_identifier', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('checklist_instances', sa.Column('completed_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('checklist_instances', sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checklist_instances', type_='foreignkey')
    op.drop_constraint(None, 'checklist_instances', type_='foreignkey')
    op.create_foreign_key(op.f('checklist_instances_template_id_fkey'), 'checklist_instances', 'checklist_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('checklist_instances_completed_by_fkey'), 'checklist_instances', 'users', ['completed_by'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_checklist_instances_template_id'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_status'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_project_id'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_area_id'), table_name='checklist_instances')
    op.alter_column('checklist_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_instances', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('checklist_instances', 'created_by')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('audit_logs_project_id_fkey'), 'audit_logs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type_entity_id'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('area_progress', 'reported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('area_progress', 'progress_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('approval_steps', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('approval_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_requests', 'current_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('approval_requests', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('findings')
    op.drop_table('equipment_approval_decisions')
    op.drop_table('approval_decisions')
    op.drop_table('inspections')
    op.drop_table('equipment_submissions')
    op.drop_table('equipment_approval_submissions')
    op.drop_table('inspection_stages')
    op.drop_table('inspection_stage_templates')
    op.drop_table('equipment_template_consultants')
    op.drop_table('inspection_consultant_types')
    op.drop_index(op.f('ix_equipment_templates_category'), table_name='equipment_templates')
    op.drop_table('equipment_templates')
    op.drop_index(op.f('ix_consultant_types_category'), table_name='consultant_types')
    op.drop_table('consultant_types')
    # ### end Alembic commands ###
