#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 023

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Fix Meeting Property Name Mismatch"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Frontend (primary service for this task)
echo -e "${YELLOW}Starting Frontend...${NC}"
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# Backend (optional - for testing API integration)
echo -e "${YELLOW}Starting Backend (optional)...${NC}"
cd backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend" || echo -e "${YELLOW}Backend not required for type-only changes${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:8000 (optional)"
echo ""
echo "This is a frontend-only refactor task."
echo "Backend is optional for API integration testing."
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Cleanup handler
cleanup() {
    echo ""
    echo "Stopping services..."
    kill $FRONTEND_PID 2>/dev/null || true
    kill $BACKEND_PID 2>/dev/null || true
    exit 0
}

trap cleanup SIGINT SIGTERM

# Keep script running
wait
