#!/bin/bash

# Auto-Build Environment Setup - Language Toggle UI Enhancement
# Generated by Planner Agent
# Spec: 112-create-language-toggle-ui

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Language Toggle UI - Add Spanish Support"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo -e "${YELLOW}Starting Frontend (React + Vite)...${NC}"
cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
fi

# Start development server in background
npm run dev:hmr > /tmp/frontend-dev.log 2>&1 &
FRONTEND_PID=$!
echo "Frontend started (PID: $FRONTEND_PID)"

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# Return to project root
cd ..

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Dev Server Logs:"
echo "  Frontend: tail -f /tmp/frontend-dev.log"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
echo "========================================"
echo "Task: Add Spanish Language Support"
echo "========================================"
echo ""
echo "What's being added:"
echo "  ✅ Spanish translation file (es.json)"
echo "  ✅ Spanish option in language toggle"
echo "  ✅ Type updates for Spanish support"
echo ""
echo "Existing features (already working):"
echo "  ✓ English translations"
echo "  ✓ Hebrew translations (with RTL support)"
echo "  ✓ localStorage persistence"
echo "  ✓ Browser language detection"
echo ""
echo "Start implementing with:"
echo "  cd frontend && npm run dev:hmr"
echo ""
