#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 030
# File Storage Local/S3 Verification and Testing

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START DATABASE AND REDIS
# ============================================

echo ""
echo "Starting PostgreSQL and Redis via Docker..."
docker-compose up -d db redis

# Wait for PostgreSQL
wait_for_service 5432 "PostgreSQL"

# Wait for Redis
wait_for_service 6379 "Redis"

# ============================================
# START BACKEND SERVICE
# ============================================

echo ""
echo "Starting Backend (FastAPI)..."
cd backend

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv venv
fi

# Activate virtual environment
source venv/bin/activate

# Install dependencies
echo "Installing Python dependencies..."
pip install -r requirements.txt > /dev/null 2>&1

# Set environment variables for local storage
export STORAGE_TYPE=local
export LOCAL_STORAGE_PATH=./uploads
export DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/builder_db

# Run database migrations
echo "Running database migrations..."
alembic upgrade head

# Start backend server in background
echo "Starting backend server on port 8000..."
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!

cd ..

# Wait for backend to be ready
wait_for_service 8000 "Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL:  localhost:5432"
echo "  Redis:       localhost:6379"
echo "  Backend:     http://localhost:8000"
echo "  API Docs:    http://localhost:8000/docs"
echo ""
echo "Storage Configuration:"
echo "  Type:        local (filesystem)"
echo "  Path:        ./backend/uploads/"
echo ""
echo "Test Commands:"
echo "  Unit Tests:        cd backend && python -m pytest tests/test_storage_service.py -v"
echo "  Integration Tests: cd backend && python -m pytest tests/integration/ -v"
echo "  All Tests:         cd backend && python -m pytest tests/ -v"
echo ""
echo "To stop services:"
echo "  1. Press Ctrl+C"
echo "  2. Run: docker-compose down"
echo "  3. Kill backend: kill $BACKEND_PID"
echo ""
