#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Add Micro-interactions to Components

set -e

echo "========================================"
echo "Starting Frontend Development Server"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo -e "${YELLOW}Installing dependencies...${NC}"
cd frontend && npm install

echo ""
echo -e "${YELLOW}Starting Vite dev server...${NC}"
npm run dev:hmr &

# Wait for frontend to be ready
wait_for_service 5173 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:5173"
echo ""
echo "Available Commands:"
echo "  - Open browser to view application"
echo "  - npm run build (in frontend/) - Build for production"
echo "  - npm run lint (in frontend/) - Lint code"
echo ""
echo "Development Notes:"
echo "  - Animations use Emotion + Material UI"
echo "  - Check browser DevTools for performance"
echo "  - Test prefers-reduced-motion in DevTools > Rendering"
echo "  - Verify 60fps in Performance tab"
echo ""
