#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Create Alembic Migration for Inspections

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START DATABASE SERVICE
# ============================================

echo ""
echo "Starting PostgreSQL database..."
cd /Users/galhadida/projects/builder_project/builder_program
docker-compose up db -d
wait_for_service 5432 "PostgreSQL"

# ============================================
# BACKEND ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking backend dependencies..."
cd /Users/galhadida/projects/builder_project/builder_program/backend

if [ ! -d "venv" ] && [ ! -d ".venv" ]; then
    echo -e "${YELLOW}No virtual environment found. Creating...${NC}"
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
else
    if [ -d "venv" ]; then
        source venv/bin/activate
    else
        source .venv/bin/activate
    fi
    echo -e "${GREEN}Virtual environment activated${NC}"
fi

# ============================================
# CHECK DATABASE CONNECTION
# ============================================

echo ""
echo "Checking database connection..."
python -c "from app.config import get_settings; s = get_settings(); print(f'Database: {s.database_url_sync}')" || echo -e "${YELLOW}Warning: Could not verify database config${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL: localhost:5432"
echo "  Database: builder_db"
echo ""
echo "Next Steps:"
echo "  1. Review implementation_plan.json for subtasks"
echo "  2. Start with Phase 1: Create SQLAlchemy models"
echo "  3. Run migrations after models are created"
echo ""
echo "Alembic Commands:"
echo "  cd backend"
echo "  alembic revision --autogenerate -m 'message'"
echo "  alembic upgrade head"
echo "  alembic downgrade -1"
echo ""
