#!/bin/bash

# Auto-Build Environment Setup - Inspection API Endpoints
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Inspection Management API Endpoints"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting PostgreSQL via Docker Compose..."
docker-compose up -d postgres redis

echo ""
echo "Waiting for database..."
wait_for_service 5432 "PostgreSQL"

echo ""
echo "Running database migrations..."
cd backend
alembic upgrade head
cd ..

echo ""
echo "Starting Backend API..."
cd backend
uvicorn app.main:app --reload --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/api/v1/docs"
echo "  PostgreSQL:   localhost:5432"
echo "  Redis:        localhost:6379"
echo ""
echo "Backend PID: $BACKEND_PID"
echo ""
echo "To stop backend:"
echo "  kill $BACKEND_PID"
echo ""
echo "To stop all services:"
echo "  docker-compose down"
echo ""
echo "========================================"
echo "Ready to implement inspection endpoints!"
echo "========================================"
