#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Add React Error Boundary for graceful crash recovery

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "frontend/node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    cd frontend && npm install && cd ..
fi

# ============================================
# START FRONTEND DEV SERVER
# ============================================

echo ""
echo -e "${YELLOW}Starting frontend dev server...${NC}"
cd frontend && npm run dev:hmr &
FRONTEND_PID=$!
cd ..

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Frontend PID: $FRONTEND_PID"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running and handle cleanup
trap "echo 'Stopping services...'; kill $FRONTEND_PID 2>/dev/null; exit 0" INT TERM

# Wait for frontend process
wait $FRONTEND_PID
