#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for RTL Layout Support Implementation

set -e

echo "========================================"
echo "Starting Development Environment"
echo "RTL Layout Support - Spec 114"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START BACKEND (Optional - for full testing)
# ============================================

echo ""
echo "Starting backend..."
cd backend
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND (Primary Service)
# ============================================

echo ""
echo "Starting frontend..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8000"
echo "  Frontend: http://localhost:3000"
echo ""
echo "RTL Testing:"
echo "  1. Navigate to http://localhost:3000"
echo "  2. Click Language toggle in header"
echo "  3. Switch to Hebrew (עברית)"
echo "  4. Verify layout mirrors correctly"
echo "  5. Compare with design-assets/29-hebrew-rtl.png"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
