#!/bin/bash

# Auto-Build Environment Setup for Spec 019
# Epic 3: Senior Supervision Inspection System
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Epic 3: Senior Supervision Inspection System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python 3 found${NC}"

# Check PostgreSQL
if ! command -v psql &> /dev/null; then
    echo -e "${YELLOW}⚠ PostgreSQL client not found (psql)${NC}"
else
    echo -e "${GREEN}✓ PostgreSQL client found${NC}"
fi

# Check Docker (optional)
if command -v docker &> /dev/null; then
    echo -e "${GREEN}✓ Docker found${NC}"
else
    echo -e "${YELLOW}⚠ Docker not found (optional)${NC}"
fi

# ============================================
# START DATABASE (if using Docker)
# ============================================

if [ -f "docker-compose.yml" ]; then
    echo ""
    echo "Starting PostgreSQL via Docker Compose..."
    docker-compose up -d postgres
    wait_for_service 5432 "PostgreSQL"
fi

# ============================================
# BACKEND SETUP
# ============================================

echo ""
echo "Setting up backend..."

cd backend

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv venv
fi

# Activate virtual environment
echo "Activating virtual environment..."
source venv/bin/activate

# Install dependencies
echo "Installing Python dependencies..."
pip install -r requirements.txt

# Install openpyxl for Excel parsing
echo "Installing openpyxl for Excel parsing..."
pip install openpyxl==3.1.5

# Run database migrations
echo "Running database migrations..."
alembic upgrade head

# Start backend server in background
echo "Starting backend server..."
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!

cd ..

wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  ReDoc:        http://localhost:8000/redoc"
echo ""
echo "Implementation Plan:"
echo "  Total Phases: 6"
echo "  Total Subtasks: 26"
echo "  Services: backend"
echo ""
echo "Next Steps:"
echo "  1. Verify backend is running: curl http://localhost:8000/health"
echo "  2. Check API docs: open http://localhost:8000/docs"
echo "  3. Start implementation with coder agent"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo ""
echo "========================================"
