#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Checklist Template API Endpoints

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Backend
echo -e "${YELLOW}Starting Backend API...${NC}"
cd backend && uvicorn app.main:app --reload --port 8000 &
wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  Swagger UI:   http://localhost:8000/docs"
echo "  ReDoc:        http://localhost:8000/redoc"
echo ""
echo "Next Steps:"
echo "  1. Open http://localhost:8000/docs to verify endpoints"
echo "  2. Look for 14 checklist endpoints"
echo "  3. Test template CRUD operations"
echo "  4. Test instance creation from templates"
echo ""
