#!/bin/bash

# Auto-Build Environment Setup
# Task 141: Add keyboard accessibility and ARIA roles to interactive Card components
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task 141: Keyboard Accessibility"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
fi

# Start frontend dev server
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "For this accessibility task:"
echo "  - Edit: src/components/ui/Card.tsx"
echo "  - Test pages: /dashboard, /projects"
echo "  - Use Tab key to navigate, Enter/Space to activate"
echo ""
echo "Stop all services with: kill $FRONTEND_PID"
echo ""
