#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 013-1-6

set -e

echo "========================================"
echo "Equipment Templates Seed Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting PostgreSQL database..."
docker-compose up -d db
wait_for_service 5432 "PostgreSQL"

echo ""
echo "Installing Python dependencies..."
cd backend
pip install -r requirements.txt

echo ""
echo "Running database migrations..."
alembic upgrade head

echo ""
echo "Starting backend service..."
cd ..
uvicorn backend.app.main:app --reload --port 8000 &
wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL: localhost:5432"
echo "  Backend API: http://localhost:8000"
echo "  API Docs:    http://localhost:8000/api/v1/docs"
echo ""
echo "Next Steps:"
echo "  1. Run seed script: cd backend && python -m app.db.seeds.equipment_templates"
echo "  2. Verify seeding: psql builder_db -c 'SELECT COUNT(*) FROM equipment_templates;'"
echo ""
echo "Note: This task is backend-only. No frontend service needed."
echo ""
