#!/bin/bash

# Auto-Build Environment Setup - Form Input Components
# Generated by Planner Agent for Spec 038

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Form Input Components Task (BUI-88)"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo -e "${YELLOW}Starting Frontend (React + Vite)...${NC}"
cd frontend
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Task: Create 6 form input components"
echo "  - TextInput"
echo "  - TextareaInput"
echo "  - SelectInput"
echo "  - CheckboxInput"
echo "  - DatePickerInput"
echo "  - FileUploadInput"
echo ""
echo "Component directory: frontend/src/components/forms/"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
echo "Press Ctrl+C to exit"
echo ""

# Keep script running
wait
