#!/bin/bash

# Auto-Build Environment Setup - Epic 2: Apartment Checklist Template System
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Epic 2: Apartment Checklist Template System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START INFRASTRUCTURE
# ============================================

echo ""
echo "Starting infrastructure services..."

# Start PostgreSQL and Redis via Docker Compose
docker-compose up -d db redis

wait_for_service 5432 "PostgreSQL"
wait_for_service 6379 "Redis"

# ============================================
# START BACKEND
# ============================================

echo ""
echo "Starting backend service..."

# Run migrations
cd backend
alembic upgrade head
cd ..

# Start backend server
cd backend
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL:  localhost:5432"
echo "  Redis:       localhost:6379"
echo "  Backend API: http://localhost:8000"
echo ""
echo "API Documentation:"
echo "  Swagger UI:  http://localhost:8000/api/v1/docs"
echo "  ReDoc:       http://localhost:8000/api/v1/redoc"
echo ""
echo "Database Commands:"
echo "  Apply migrations:  cd backend && alembic upgrade head"
echo "  Create migration:  cd backend && alembic revision --autogenerate -m 'description'"
echo "  Rollback:          cd backend && alembic downgrade -1"
echo ""
echo "Ready to implement Epic 2: Checklist Template System"
echo "========================================"
