#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Create InspectionTemplate SQLAlchemy Models

set -e

echo "========================================"
echo "Inspection Template Models - Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT VERIFICATION
# ============================================

echo ""
echo "Verifying backend Python environment..."
cd backend

# Check Python version
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python3 not found. Please install Python 3.8+${NC}"
    exit 1
fi

PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}✓ Python $PYTHON_VERSION${NC}"

# Check if requirements are installed
if ! python3 -c "import fastapi" 2>/dev/null; then
    echo -e "${YELLOW}Installing backend dependencies...${NC}"
    pip3 install -r requirements.txt
fi

# Verify SQLAlchemy is available
if ! python3 -c "import sqlalchemy" 2>/dev/null; then
    echo -e "${RED}SQLAlchemy not installed. Run: pip3 install -r requirements.txt${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Backend dependencies installed${NC}"

# ============================================
# DATABASE VERIFICATION (Optional)
# ============================================

echo ""
echo "Checking database connection..."
if nc -z localhost 5432 2>/dev/null; then
    echo -e "${GREEN}✓ PostgreSQL running on port 5432${NC}"
else
    echo -e "${YELLOW}⚠ PostgreSQL not detected on port 5432${NC}"
    echo -e "${YELLOW}  Note: Database is not required for model creation, only for migration${NC}"
fi

# ============================================
# START SERVICES (Optional for this task)
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Model Creation"
echo "========================================"
echo ""
echo "This task creates SQLAlchemy models only."
echo "No services need to be running for implementation."
echo ""
echo "Services (for testing after implementation):"
echo "  Backend:  http://localhost:8000"
echo "  Database: postgresql://localhost:5432"
echo ""
echo "To start backend server (optional):"
echo "  cd backend && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "To start database:"
echo "  docker-compose up -d db"
echo ""
