#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 075: Landing Page Hero Section

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 075: Landing Page Hero Section"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Frontend (React + Vite)
echo -e "${YELLOW}Starting Frontend Service...${NC}"
cd frontend
npm run dev:hmr &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Development Notes:"
echo "  - Frontend uses Vite with HMR for fast refresh"
echo "  - Design reference: design-assets/landing/01-hero-dark.png"
echo "  - MUI + styled() API pattern (not Emotion directly)"
echo ""
echo "To stop services, press Ctrl+C"
echo ""

# Keep script running
wait $FRONTEND_PID
