#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 102-implement-transition-system

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Frontend Development Server..."
echo "----------------------------------------"

# Navigate to frontend directory and start dev server
cd frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Start the development server
npm run dev &

# Wait for the server to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Note: Backend not required for page transition feature"
echo ""
echo "To stop all services:"
echo "  ps aux | grep 'npm run dev' | awk '{print \$2}' | xargs kill"
echo ""
