#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 143

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Fix Header Settings Navigation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Frontend Development Server..."
echo "----------------------------------------"

# Check if we're in the correct directory
if [ ! -d "frontend" ]; then
    echo -e "${RED}Error: frontend directory not found${NC}"
    echo "Please run this script from the project root"
    exit 1
fi

# Install dependencies if node_modules doesn't exist
if [ ! -d "frontend/node_modules" ]; then
    echo "Installing frontend dependencies..."
    cd frontend && npm install && cd ..
fi

# Start frontend dev server
cd frontend && npm run dev &
FRONTEND_PID=$!
cd ..

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Task Details:"
echo "  - Create SettingsPage component"
echo "  - Add /settings route to App.tsx"
echo "  - Update Header to navigate instead of showing toast"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
echo "Press Ctrl+C to stop all services"
echo "========================================"

# Keep script running
wait $FRONTEND_PID
