#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 139: Add aria-label to IconButton components

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Add aria-label to IconButtons"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd ./frontend

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
fi

# Start frontend dev server in background
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Process IDs:"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $FRONTEND_PID"
echo ""
echo "Task Details:"
echo "  - 29 IconButton instances to update"
echo "  - 15 files to modify"
echo "  - Add aria-label attributes for accessibility"
echo ""
echo "Next Steps:"
echo "  1. Open files in ./frontend/src"
echo "  2. Add aria-label props to IconButton components"
echo "  3. Test with screen reader or DevTools"
echo "  4. Run 'npm run build' to verify TypeScript"
echo ""
