#!/bin/bash

# Auto-Build Environment Setup
# Remove Non-Functional Filter Buttons
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Filter Button Cleanup Task"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd ./frontend

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start frontend
echo "Frontend starting on port 3000..."
npm run dev:hmr &
FRONTEND_PID=$!

cd ..

# Wait for frontend
wait_for_service 3000 "Frontend Application" || {
    kill $FRONTEND_PID 2>/dev/null || true
    exit 1
}

# ============================================
# CLEANUP FUNCTION
# ============================================

cleanup() {
    echo ""
    echo "Shutting down services..."
    kill $FRONTEND_PID 2>/dev/null || true
    echo "Done."
}

trap cleanup EXIT INT TERM

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  Frontend: ${GREEN}http://localhost:3000${NC}"
echo ""
echo "Task: Remove non-functional Filter buttons from 7 pages"
echo ""
echo "Pages to verify:"
echo "  - http://localhost:3000/projects"
echo "  - http://localhost:3000/rfi"
echo "  - http://localhost:3000/equipment"
echo "  - http://localhost:3000/inspections"
echo "  - http://localhost:3000/materials"
echo "  - http://localhost:3000/approvals"
echo "  - http://localhost:3000/contacts"
echo ""
echo "What to verify:"
echo "  1. Filter button is removed from each page"
echo "  2. Search field still works"
echo "  3. Tab filtering still works"
echo "  4. No console errors"
echo ""
echo "Press Ctrl+C to stop the frontend"
echo ""

# Keep script running
wait $FRONTEND_PID 2>/dev/null || true
