#!/bin/bash

# Auto-Build Environment Setup
# Make Skeleton Loading Grids Responsive
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Skeleton Loading Grids - Responsive Fix"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (React + Vite)..."
cd ./frontend

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start frontend
echo "Frontend starting on port 3000..."
npm run dev &
FRONTEND_PID=$!

cd ..

# Wait for frontend
wait_for_service 3000 "Frontend Application" || {
    kill $FRONTEND_PID 2>/dev/null || true
    exit 1
}

# ============================================
# CLEANUP FUNCTION
# ============================================

cleanup() {
    echo ""
    echo "Shutting down services..."
    kill $FRONTEND_PID 2>/dev/null || true
    echo "Done."
}

trap cleanup EXIT INT TERM

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  Frontend: ${GREEN}http://localhost:3000${NC}"
echo ""
echo "Task: Make Skeleton Loading Grids Responsive"
echo ""
echo "What to do:"
echo "  1. Open http://localhost:3000 in your browser"
echo "  2. Test pages with skeleton loading states:"
echo "     - /projects"
echo "     - /dashboard"
echo "     - /projects/:id/contacts"
echo "     - /projects/:id (and other subpages)"
echo "  3. Use browser DevTools to test different viewport sizes:"
echo "     - Mobile: < 600px"
echo "     - Tablet: 600-960px"
echo "     - Desktop: > 960px"
echo "  4. Reload pages and observe skeleton loading state"
echo "  5. Verify no layout shift when data loads"
echo ""
echo -e "${YELLOW}Note:${NC} Backend is not needed for this UI-only task."
echo -e "If you need real data, you can start the backend separately."
echo ""
echo "Press Ctrl+C to stop the frontend service"
echo ""

# Keep script running
wait $FRONTEND_PID 2>/dev/null || true
