#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Mobile Inspection Checklist Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Mobile Inspection Checklist Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python not found. Please install Python 3 first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python $(python3 --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Frontend dependencies
if [ -d "frontend" ]; then
    echo "Installing frontend dependencies..."
    cd frontend
    if [ ! -d "node_modules" ]; then
        npm install
    fi

    # Check if react-signature-canvas is installed
    if ! npm list react-signature-canvas &> /dev/null; then
        echo -e "${YELLOW}Installing react-signature-canvas...${NC}"
        npm install react-signature-canvas @types/react-signature-canvas
    else
        echo -e "${GREEN}✓ react-signature-canvas already installed${NC}"
    fi
    cd ..
else
    echo -e "${RED}Frontend directory not found!${NC}"
    exit 1
fi

# Backend dependencies (optional check)
if [ -d "backend" ]; then
    echo "Backend directory found - backend already configured"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Backend (if needed)
if [ -d "backend" ]; then
    echo "Starting backend..."
    cd backend
    if [ -f "venv/bin/activate" ]; then
        source venv/bin/activate
        uvicorn app.main:app --reload --port 8000 &
        cd ..
        wait_for_service 8000 "Backend API"
    else
        echo -e "${YELLOW}Backend venv not found - skipping backend startup${NC}"
        echo -e "${YELLOW}Backend APIs expected to be available at http://localhost:8000${NC}"
        cd ..
    fi
fi

# Frontend
echo "Starting frontend..."
cd frontend
npm run dev &
FRONTEND_PID=$!
cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
if [ -d "backend" ]; then
    echo "  Backend API:  http://localhost:8000"
    echo "  API Docs:     http://localhost:8000/docs"
fi
echo "  Frontend:     http://localhost:3000"
echo ""
echo "Mobile Checklist Routes:"
echo "  /projects/{projectId}/inspections/{inspectionId}/checklist"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $FRONTEND_PID
