#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Equipment Approval Models Task

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Start PostgreSQL (via Docker Compose)
echo -e "${YELLOW}Starting PostgreSQL database...${NC}"
docker-compose up -d db

# Wait for database
wait_for_service 5432 "PostgreSQL"

# Backend Service
echo -e "${YELLOW}Starting Backend API...${NC}"
cd backend

# Install dependencies if needed
if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment..."
    python -m venv venv
fi

# Activate virtual environment
source venv/bin/activate

# Install requirements
pip install -r requirements.txt

# Run migrations
echo "Running database migrations..."
alembic upgrade head

# Start backend server
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &

cd ..

wait_for_service 8000 "Backend API"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Database:  postgresql://localhost:5432"
echo "  Backend:   http://localhost:8000"
echo "  API Docs:  http://localhost:8000/docs"
echo ""
echo "To stop all services:"
echo "  docker-compose down"
echo "  pkill -f uvicorn"
echo ""
